### ISSUE TITLE
Top menu content

### ISSUE THREAD

**Issue by DarkXero-dev** [XeroLinuxDev/xerolinux.xyz#11]
For the top menu I want, YouTube, Forum, Wiki and Merch links

Merch : https://store.streamelements.com/xerolinux

**Comment by jajunk** [comment]
I need the link for the forum website. Paste it into the response here.

**Comment by DarkXero-dev** [comment]
Forum
https://forum.xerolinux.xyz/

**Comment by jajunk** [comment]
Fix in Merge #18
