### ISSUE TITLE
Download Button Pop Up

### ISSUE THREAD

**Issue by jajunk** [XeroLinuxDev/xerolinux.xyz#16]
- Small Information blurb
- Link to Release Notes?
- Changelog
- Donate Button
- Second Pop Up with Curl Command
- GitHub Build from source

![Xero Site Second Pop Up](https://github.com/XeroLinuxDev/xerolinux.xyz/assets/34286612/a38df6e7-d627-4828-a7c5-73de7d52ad4d)

![Xero Site Pop Up 1](https://github.com/XeroLinuxDev/xerolinux.xyz/assets/34286612/312ecf42-a06c-4817-b1e3-64ed60ce6d19)

**Comment by DarkXero-dev** [comment]
We already talked bout this my friend all this has to go.. Site will be single page with the only popup being the donate button.. You getting so old you forgetting ? Curl command is not a popup it should be just like Kudu's version on temp site. Basically final site will be just like Kudu's with only popup being the donate button with the 3 options.. Same as Moh.'s version.. 

Maybe changelog popup with info I put in there for now. I will change later myself.. 

Use same blurbs as current temp site.. With socials as I showed you before in footer..

**Comment by jajunk** [comment]
I get it. We talked about it. I had it confused. I thought you still wanted the pop up to be the curl command with the donate button below it.

**Comment by DarkXero-dev** [comment]
It's fine. We all forget things...
